const path=require('path')
console.log(path.sep)
const filepath=path.join('content','subfolder','test.txt')
console.log(filepath)
const absolute=path.resolve(__dirname,filepath)
console.log(absolute)
const base=path.basename(absolute)
console.log(base)